### ISSUE TITLE
Python compatibility

### ISSUE THREAD

**Issue by ghost** [liamcurry/py3kwarn#1]
I can help out here, setting up tox, figuring out what Python versions this is compatible with, and fixing versions that should be supported.

What versions are you looking to support, 2.6 and 2.7?

**Comment by liamcurry** [comment]
So far it's compatible with 2.7+. In lower versions the implementation of `lib2to3` is either different or non-existant. This is okay for me since I only use 2.7+ anyway, but I've considered bundling the `lib2to3` module with `py3kwarn` to support users with older versions.

~~I've never used tox -- are there benefits to it over [travis](https://travis-ci.org/liamcurry/py3kwarn)?~~ I just took a look at the tox documentation. It'd actually be really nice to have this!

I am open to suggestions, and contributions are appreciated. Here's my [todo list](https://github.com/liamcurry/py3kwarn#todo) if you're looking for a way to help. Thanks!
